### ISSUE TITLE
Huge localization issues.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentsGems-TiCSupport#1]
### Versions (Key~ u- = Universal / -b = beta)
 
Minecraft Version: 1.12.2
Silent's Gems Version: u-SilentsGems-1.12.2-2.8.0-286-b
Silent's Gems - TiC Version: u-SilentsGems-TiC-1.12.2-0.1.0-2-b

### Expected behavior

Actual Names and proper localization

### Actual behavior

Programmers Item Names and none localization

### Steps to reproduce the problem

Run.
![2018-08-19 00_53_08-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/44305971-a53dd380-a34a-11e8-89aa-809c1f03c86e.jpg)

**Comment by SilentChaos512** [comment]
Right, I changed all the translation keys... I'll get it fixed. Should be released either tonight or tomorrow.
